### ISSUE TITLE
Check plot.netdx in model with many summary stats

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel#270]
qnts.alpha seems to get lower as the stats increase
mean.col does not seem to have an effect
actually, passing qnts.col or mean.col seems to have the effect of not plotting that component

**Comment by smjenness** [comment]
When `plots.joined = FALSE`, just make a single clear color for all stats (no need for color separation).

**Comment by connor-vanmeter** [comment]
Re: qnts.alpha getting lower as the stats increase:
The issue appears to lie with qnts.col <- transco(qnts.col, qnts.alpha)

When qnts.col is missing, it is set to sim.col.
In my investigation, I set sim.col as a vector of size 'nstats' with all positions of the vector being color "#377EB8" (second color in "Set1" palette).
With nstat = 1, qnts.col <- transco(sim.col,qnts.alpha) since qnts.col is missing.
With every subsequent nstat plot, qnts.col is no longer missing and so does not get set to sim.col.  
Instead, qnts.col (nstat(n+1)) <- Transco(qnts.col (ntat(n)), qnts.alpha)

The color becomes more transparent with each nstat plot.

**Comment by connor-vanmeter** [comment]
To do:
1. Address qnts.col <- transco(qnts.col, qnts.alpha)
2. Black mean line
