### ISSUE TITLE
Organization of EpiModel literature

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel#367]
@martinamorris @sgoodreau @AdrienLeGuillou @connor-vanmeter @andsv2 @ejanderson1 

Currently I curate a list of published (and pre-print) studies that have used EpiModel (not just cited it) on the following list:
https://github.com/statnet/EpiModel#epimodel-in-the-scientific-literature

As the list is growing, I would like a more sustainable to maintain and easier to read approach. Please brainstorm below.

**Comment by AdrienLeGuillou** [comment]
Maybe it could be interesting to have on GitHub only a limited amount of articles to showcase the use of EpiModel, like the 5 to 10 most recent or most important papers. And a link to an external library with all the references. We could have a public Zotero library with closed membership so anyone could view but not edit it.

**Comment by ejanderson1** [comment]
I like Adrien's idea. Another option might be to create different files for various types of articles and putting links in there. So for example, one file for HIV and other STIs. If possible, they could go into a literature folder.

**Comment by sgoodreau** [comment]
I agree that having it in a bibliography file of some form or other will get increasingly useful as it gets bigger. 

I guess the ultimate question is: what are the purposes of having the list?  I imagine:

(1) for you own interest
(2) to be able to tell future grant (and/or manuscript) reviewers about the magnitude of the fruits of your labor
(3) to give potential users a sense of the range of different ways EpiModel is applied, with concrete examples, to inspire them to use it and help them get started
(4) to give potential users a comprehensive list of all the ways it's been used, so they can see if there are others in a similar domain to reach out to / start their code off of

I agree with Adrian's suggestion, since it seems that the short list of highlights (chosen for breadth as well as quality and recency) covers (3) while the bibliography file covers (1,2,4).

**Comment by smjenness** [comment]
Closed with #418
