### ISSUE TITLE
Add github dependencies to DESCRIPTION file?

### ISSUE THREAD

**Issue by martinamorris** [statnet/EpiModel#422]
As a package develops, but is not yet on CRAN, it's often the case that it depends on other packages that are also not yet on CRAN.

To use `remotes::install_github`, you often need to be careful about these package dependencies -- to make sure a consistent set of packages is installed (for example `ergm@master` needs `network@master` and `statnet.common@master`).  

Those dependencies can be *automatically* installed, by including a line in the `DESCRIPTION` file (in the GH repo) identifying the `remotes` to check.  

Pavel has now included that line in all of the `statnet` package `DESCRIPTION` files:  [here is an example](https://github.com/statnet/ergm-private/blob/cf0a45a2b8107ba44a97d101bceba0bf35ac55a0/DESCRIPTION#L173-L174).

This takes some of the load off the user to identify a consistent install stack.  Might be worth considering for EpiModel.

**Comment by smjenness** [comment]
Interesting, I wasn't aware of this. Thanks.

@andsv2 : would you please take a look into this, and see if it works for our current EpiModel2 setup across EpiModel, tergmLite, and the EpiModelGallery (not sure it's relevant to the last since it's not a package) given the current calls for these dependencies on the .travis.yml's?

**Comment by martinamorris** [comment]
One other thing -- I believe this `remotes` line must be deleted when publishing to CRAN.

**Comment by smjenness** [comment]
everything for EpiModel 2 will be merged into master today, so closing this
