### ISSUE TITLE
New required control input for EpiModel::saveout.net

### ISSUE THREAD

**Issue by dth2** [statnet/EpiModel#428]
I am trying to run simulation using EpiModelHIV, started with an older base set of code, and the simulation runs fine with all of the master versions of all thing statnet and EpiModel right up until I go to save the output.  EpiModel::saveout.net now requires an additional control parameter "control$tergmLite" or the simulation crashes.  I have tried specifying control$tergmLite == FALSE and TRUE and it doesn't seem to make a difference.  What is this control supposed to be doing and would it make sense to have a default if it is not specified? 

Thanks
Deven

**Comment by AdrienLeGuillou** [comment]
I am confused because the new `control.net()` function gives a default value to `control$tergmLite`. Are you using the new functions while re-using a saved `control` object?

Maybe you can give us more info on your setup:

- did you re-run the `init()`, `param()` and `control()` or are you reusing previously created `init`, `param` and `control` objects?
- are you using `tergmLite` for your project?
- are you using custom modules?
    - if yes, do you have a custom init module

**Comment by dth2** [comment]
I am using init() , param(), and control() functions from an older version of EpiModelHIV.  I have reverted to EpiModel 1.8 and everything is working.
