### ISSUE TITLE
progress tracker for netsim with nsim>1 (feature request)

### ISSUE THREAD

**Issue by ThomasKraft** [statnet/EpiModel#458]
Running `netsim` with `nsims = 1`  creates a very helpful progress tracker in the output as the function runs (reports # out of total steps completed). This is especially useful when running large networks with custom modules that are fairly slow.

When setting `nsims` > 1, however, this feature does not appear. Would it be possible to extend this feature to such cases? Presumably this may not yet be done because having a tracker for every single simulation running simultaneously on multiple cores would create a large amount of output. One alternative would be to just print output for one of the simulations as an approximation, create a more compact output, or allow users to hide the verbose output.

**Comment by smjenness** [comment]
Hi @ThomasKraft : the issue is not when nsims > 1, but when ncores > 1. I would concerned about implementing a general solution here that would work for larger research-level models (thousands of simulations on hundreds of cores on an HPC) without generating massive stdout files (what captures the output in R batch mode). But the output is handled with the "verbose module", the default of which is here: https://github.com/statnet/EpiModel/blob/master/R/verbose.R#L98-L129. And so you can edit that to your needs, and pass in the new function into the control settings (control.net) with the verbose.FUN parameter.

**Comment by ThomasKraft** [comment]
Perfect, thanks for the quick reply. Very flexible solution!
