### ISSUE TITLE
Time-varying attribute storage

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel#478]
Based on feature request from @adam-s-elder: 
* A list that would store agent attributes for each time step, mainly for model debugging/validation purposes. Internal storage could be list of matrices:
     - rows (IDs) x columns (time steps)
     - one matrix (list element) for each attribute
     - stored as `dat$attr_hist`
* Control setting would character vector of attributes to store like this
* Direct copy from `dat$attr` at each time step
* One complication is how to handle mortality, which drops values from `dat$attr`
     - Could use `uid` throughout
* Saved in final `netsim`, with accessor function `get_attr_hist` transforming into a tidy data frame for easy analysis

**Comment by adam-s-elder** [comment]
Thanks for opening this issue @smjenness.

One other thing I was thinking of is that for most variables you don't need to know the attrs at every step, so whichever process you use you could just create a direct copy each year or so.  So there could be an additional control setting where you specify the granularity of these saves.

Also, to limit the memory pressure from doing this I was thinking of a different way of storing these things (since on most time steps, for any given attribute, it probably won't change much (maybe besides age)).  Maybe I am saying the same thing as you, but this is what my idea was.

You have a data frame that would look like this:

| uid | step | attr | from | to | 
|----|------|-----|------|-------|
| 1241 | 54 | status | 0 | 1 |
| 1783 | 66 | tx | 1 | 0 |

Then after the simulation was run, you would use the attribute list (you would also need to store the attribute list of dropped nodes) from the end of the simulation.  Then, if, say I wanted to know the status of 1241 at step 52, the get_attr_hist would start with 1, but look at the above data frame and swap the attribute status from 1 to 0 (undoing what happened during the simulation).  

This would require more calculation to be done post simulation, but would cut down a lot on the storage during the simulation.  There would also be a few other issues, like that you would need to store two sets of attr lists, but I think this way of storing things would still be more memory efficient.

**Comment by AdrienLeGuillou** [comment]
@adam-s-elder what you suggest may require high computations as it implies checkeing each (logged) attribute for change at each time step. I think @smjenness option would be more efficient even though it could be limited to a small number of attributes to log as the size would grow quickly.

The feature explored in this issue: #386 might be of interest for this purpose as well.

**Comment by ThomasKraft** [comment]
This is a feature that would be very helpful to me as well. An inefficient workaround I've been using for post-hoc validation is to set a dynamic attribute within a module using `activate.vertex.attribute` that creates a mirror copy of the attribute that I'm interested in tracking, and saving it to `dat$nw[[1]]`. Perhaps this is useful in the meantime.

**Comment by AdrienLeGuillou** [comment]
@smjenness, @ThomasKraft, @adam-s-elder 

I am working on an implementation for what is discussed here in #532. Could you take a look at whats discussed there to see if this would fit your use cases? The implementation itself is pretty easy but I want to make sure that it will work for you.

**Comment by ThomasKraft** [comment]
Yes, that will be perfect for my use case. I am a bit confused however by the use of `pivot_wider` to transform the data from long to wide format -- how exactly will the timestep be stored in that format? Will it be a list of wide format dataframes (1 for each timestep)?

**Comment by smjenness** [comment]
@AdrienLeGuillou : I have reconsidered, I think it may be better to output in "long" format. If we/I want to reshape to wide, I can handle that outside of EpiModel myself.

**Comment by ThomasKraft** [comment]
FWIW long format is typically what I would be converting to as a user anyways, and no dependency required.

**Comment by AdrienLeGuillou** [comment]
@smjenness : ok. I will add to the documentation examples of how to go from the long to the wide format

**Comment by AdrienLeGuillou** [comment]
closed by #532
