### ISSUE TITLE
Varying activity rate in param.net based on disease status

### ISSUE THREAD

**Issue by jschon637** [statnet/EpiModel#479]
Hello, if I understand correctly, I should now be directing questions here instead of the email list. I am trying to figure out how to set a different activity rate based on different disease statuses. For example, how would I set an activity rate of 1 for a Susceptible person and an activity rate of 0.5 for an infected person in an SIS model?

**Comment by smjenness** [comment]
Yes, this is the right place to direct questions. 

Attribute-specific act rates get a little complicated because acts (or contacts or exposures, depending on the disease of interest) are a property of a dyad (pairs of individuals), each member of which can have a different attribute. So either the act rates depend on combinations in the dyad (SI vs SS vs II, for example) or you decide that one attribute "controls" (e.g., if S have lower act rates, and either person is S, then both get the act rates of S). 

In either case, this involves a relatively simple modification of the infection module. Here's a relatively straightforward template for that: https://github.com/EpiModel/EpiModelCOVID/blob/master/R/mod-infection.R#L64-L70. Here, we are modifying the act rates depending on the disease diagnosis status of the infected member of the pair. 

Hope that helps!

**Comment by jschon637** [comment]
Thank you so much! This is very helpful.
