### ISSUE TITLE
edges correction in demography changing population 

### ISSUE THREAD

**Issue by DamienGeorges** [statnet/EpiModel#487]
Hi all,

I would like to make the overall mean degree conservation assumption in EpiModel, to be age specific.

I will try to explain below the issue I am facing.

I am modelling the transmission of HPV infection in population where demographic parameters (age specific death rate, birth rate, ..) are changing drastically along the simulation. Then the final age structure of the population is very different from the one I start with. The probability of being in a partnership is strongly inflence with the age of the individuals (e.g mariage). 

EpiModel handle well the change in population size if the age structure is conserved along the simulation (or if probability to be in a partnership is independent of the age of the individuals) using the overall mean degree conservation hypothesis (via `edge_correct()` function). This hypothesis is not really satisfying in my case. I would like to reimplement `edge_correct()` function according to a per age group mean degree conservation. 

Would you be able to provide me some guidance to modify `edge_correct()` to meet this hypothesis?

To illustarte it , here a conceptual example:

Here an example of population where age distribution changes between the begining and the end of the simulation:

![image](https://user-images.githubusercontent.com/9448889/101812835-30df5d80-3b1c-11eb-9f4e-820b0838bfab.png)

With mean degree conservation hypothesis (EpiModel) I will get this degee distribution:

![image](https://user-images.githubusercontent.com/9448889/101813185-ae0ad280-3b1c-11eb-9754-387a2fa24f8b.png)

The overall mean degree is conserved but not the age group specific one.

I would like to get something like:

![image](https://user-images.githubusercontent.com/9448889/101813390-f629f500-3b1c-11eb-89a1-88beb8b3141b.png)

Hoping my request make sens,

Best,
Damien

**Comment by martinamorris** [comment]
Hi Damien,

One question -- do you have an age term in the model?

**Comment by DamienGeorges** [comment]
Hi Martina,

Indeed. The formula I am using is the following one:

```
 ~ edges + 
    absdiffby("age", "sex.id", 6.34) +
    nodefactor(c("ageg.id"), levels = c('2', '3')) +
    nodefactor(c("sex.id", "ageg.id"), levels = c('0.4', '0.5')) +
    nodefactor("riskg.id", levels = c('1', '4', '5')) +
    nodematch("sex.id", diff = FALSE) +
    degrange(c(2))
```

where: 

- **age** is the age of the individuals (continuous)
- **ageg.id** is the age group of the individual (2: <15, 3: 15-19, 4: 20-24, 5: 25-29, 6: 30-49, 7: >50)
- **sex.id** is gender of the individual 0 for women, 1 for men
- **riskg.id** is the group of sexual activity of the individuals (0 to 5)

Some coefficients of the formula are set to Inf to set constraint to the model (e.g. no partnership before age 15, purely heterosexual and monogamous network, ...)

The fit I a get out of netest is good and match very well the women mean degree per age group. This matching is not observed anymore out of netsim when I add demographics and population aging modules.

Does it make sens?

Best,
Damien

**Comment by martinamorris** [comment]
Thanks Damien -- that makes sense.

I don't have time to dig deeply into this right now, but I know what you're trying to do.  I'll need to ask @krivit if there is a way to add a mean degree x age constraint into an ERGM.

**Comment by krivit** [comment]
In principle, that the mean degree changes with age distribution is a feature, not a bug: loosely, the mean degree between two groups of actors is a product of the "preferences" (expressed by ERGM parameters) and the "availability" (the number of dyads between these groups divided by network size). (See Krivitsky, Handcock, Morris 2011.)

To force the mean degree to be constant under changing population composition is a different problem. The first idea that comes to mind is to fit an ERGM to both composition and write a term whose coefficient varies with network size such that it interpolates the two fits somehow.

**Comment by martinamorris** [comment]
This is fundamentally a theoretical issue -- what is preserved when population size and composition change?  ERGMs allow you to preserve the overall mean degree (with the edges correction), and the odds ratios for selective mixing under changing composition of the population by attribute.  As Pavel notes, this is a feature, in the sense that it avoids the the need to select one of the other ends of the continuum (each group preserves mean degree, but changes their selection of partners, or each group preserves the exact composition of their partner pool, but modifies their mean degree -- potentially to zero).

Writing a term, or a constraint, to preserve group-specific mean degree might be possible (not something I would know how to do without a fair amount of digging).

But I think the other hack here, since you're working with egocentric data, is to modify the target statistics so that they reflect the assumptions you want, and then fit the ERGM to those stats.

You can get the target stats from summary(nw ~ model terms).  Modifying them must be done with care given the dependencies among them.  But the process of doing this would highlight exactly the difficulties and issues involved in forcing assumptions like this on the dynamic process.  If the mean deg of one degree must be maintained, along with the overall mean deg, then the mean deg of other groups will have to change to make this happen.

Before `ergm.ego` we constructed all of our target stats by hand, in excel worksheets!,  and @smjenness has developed a more principled, model based approach to doing this now.  In essence, it calculates the target stats as simple functions of the netsize, number of ties, and expected proportion of ties (in the original egodata) of this type.  The expected proportions can be based on simple logistic regressions.  An example from some code I built following Sam's approach below.

```
 num <- net.size
  
  ## edges
  out$edges <- num * modpred$md.inst / 2
  
  ## nodefactor("race")
  out$nodefactor_race <- num * attrdist$race$prop * modpred$nf.race
  
  ## nodematch("race")
  out$nodematch_race <- out$nodefactor_race/2 * modpred$nm.race
  
  ## nodematch("race", diff = FALSE)
  out$nodematch_race_unif <- out$edges * modpred$nm.race_unif

```
Note that the values of these target stats have implicit constraints, for example:  sum(nodefactor) = edges.

The expressions above are intended to reproduce the network statistics that ERGM would have calculated on the complete net of size `num`.  But you can probably modify them to produce the specific netstats that reflect the assumptions you want to use.

HTH.  LMK.

**Comment by DamienGeorges** [comment]
Dear Martina and Pavel,

Thanks a lot for our thoughtful and detailed replies. Very appreaciated!

I think that implementing a specific term to maintain specific group mean degree is a bit out of my competencies field right now but I will keep that in mind.

I will then first try to apply Martina's hack to my data. 

I will keep you posted on how it goes.

Many thanks,
Damien
