### ISSUE TITLE
extract.summary.stats --> save.nwstats

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel#540]
avoid different argument names for full tergm versus tergmLite approaches

**Comment by chad-klumb** [comment]
IIRC the issue was cross-network terms.

If we want true end-of-timestep summary stats, we will need to initialize all the models twice: once to simulate, and again after simulation to update the nodal degrees in the other networks.  That will mean twice as much ergm_model time if you want generative model statistics.

This is mostly an EpiModelHIV/multiple network concern so we could probably relocate the summary call in core EpiModel and worry about such technicalities later.

**Comment by smjenness** [comment]
Ok - yes, for core EpiModel, we can just have these run after the network resimulation because there are, for now, no multi-layer networks and no cross-product terms. We'll have to figure out a way to implement that differently in EpiModelHIV.
